version: "2"
services:
  postgres:
    image: "postgres"
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - /home/ro/Databases/postgres:/var/lib/postgresql/data

  cccm:
    image: "rodocker/cccm:latest"
    container_name: cccm
    ports:
      - "8000:8000"
    environment:
      - CONN_STR=host=postgres dbname=cc user=postgres

  ccclient:
    image: "rodocker/ccclient:latest"
    container_name: ccclient
    ports:
      - "80:80"
    environment:
      - REACT_APP_API_URL=http://roazure.southcentralus.cloudapp.azure.com:8000
