version: "2"
services:
    postgres:
        image: postgres
        container_name: postgres
        environment:
            - TZ=America/Mexico_City
            - PGTZ=America/Mexico_City
            - POSTGRES_PASSWORD=<SET_PASSWORD_HERE>
        volumes:
            - /home/ro/Databases/postgres:/var/lib/postgresql/data
        ports:
            - 5432:5432
        restart: unless-stopped