version: "3.5"
services:
  postgres:
    image: "postgres"
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - /home/ro/Databases/postgres:/var/lib/postgresql/data
    networks:
      - ro-db-network
networks:
  ro-postgress-network:
    name: ro-db-network
