version: "3.5"
services:
  mssql:
    image: "mcr.microsoft.com/mssql/server:2017-latest"
    container_name: mssql
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "SqlDevOps20!7"
      ACCEPT_EULA: "Y"
      MSSQL_PID: Developer