version: '3'
services:
  portainer:
    image: "portainer/portainer:latest"
    container_name: portainer
    volumes:
      - /home/ro/Databases/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9000:9000
