version: '2'
services:
  app:
    image: matomo:fpm-alpine
    restart: always
    volumes:
      - /home/ro/Databases/matomo/app:/var/www/html
    environment:
      - MATOMO_DATABASE_HOST=mariadb
      - MYSQL_ROOT_PASSWORD=tupinchekola
      - MYSQL_PASSWORD=tupinchekola
      - MYSQL_DATABASE=matomo
      - MYSQL_USER=matomo
      - MATOMO_DATABASE_ADAPTER=mysql
      - MATOMO_DATABASE_TABLES_PREFIX=matomo_
      - MATOMO_DATABASE_USERNAME=matomo
      - MATOMO_DATABASE_PASSWORD=tupinchekola
      - MATOMO_DATABASE_DBNAME=matomo

  web:
    image: nginx:alpine
    restart: always
    volumes:
      - /home/ro/Databases/matomo/app:/var/www/html:ro
      # see https://github.com/matomo-org/matomo-nginx
      - /home/ro/Databases/matomo/nginx/matomo.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 8080:80

